### ISSUE TITLE
Tracker for hxArduino v2.0

### ISSUE THREAD

**Issue by 0xF6** [ianharrigan/hxArduino#14]
## Uploading firmware into devices
- [ ] #12, #9 Fix uploading directly via Serial Port, replace legacy hxSerial with new library (or trying fix hxSerial [hxSerial#11](https://githib.com/hxSerial/pull/11))
- [x] Add support to uploading firmware via ArduinoSDK (#15)
- [x] Add more boards support (#15)
## Improvement C++ code generation
- [ ] Implement support haxe std features (List, Map, etc)
- [ ] ~(research) Porting hashlink or nekovm into AVR\SAM platform~ (declined: gc-implementing too hard)
- [ ] (research) Add initial support reflection
- [ ] (research) auto generation typing for selected arduino-library

## Improvement Core
- [ ] Split hxArduino compiler and 'typing' library

## DevOps
- [ ] Configure Github actions for building\testing and deploying into haxelib registry

## Advertising company
- [ ] Write 2-3 articles on habr\medium to attract new users and contributors

**Comment by 0xF6** [comment]
@ianharrigan any other suggestions?
